FROM ubuntu
RUN apt update -y 
RUN mkdir tomcat
WORKDIR tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz .
RUN tar -xvzf apache-tomcat-9.0.80.tar.gz
RUN mv apache-tomcat-9.0.80/* /tomcat
EXPOSE 8082
RUN chmod +x /tomcat/bin/catalina.sh
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
